/*
 © 2015 Qualifio SPRL <www.qualifio.com> Uses
 github.com/davidjbradshaw/iframe-resizer
 @author Xavier De Cock
 Call Method
 (function(b,o,n,u,s){var a,t;a=b.createElement(u);a.async=1;a.src=s;t=b.getElementsByTagName(u)[0];t.parentNode.insertBefore(a,t);o[n]=o[n]||[]})
 (document,window,'_qual_async','script','//player.qualifio.com/kit/qualp.2.1.js');
 _qual_async.push(['FunctionName', 'args', ...]);
*/
Array.prototype.reduce||(Array.prototype.reduce=function(C){if(null==this)throw new TypeError("Array.prototype.reduce called on null or undefined");if("function"!==typeof C)throw new TypeError(C+"  is not a function");var D=Object(this),N=D.length>>>0,E=0;if(2==arguments.length)var P=arguments[1];else{for(;E<N&&!(E in D);)E++;if(E>=N)throw new TypeError("Reduce without an initial Value");P=D[E++]}for(;E<N;E++)E in D&&(P=C(P,D[E],E,D));return P});
String.prototype.trim||function(){var C=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(C,"")}}();
(function(){function C(){t[l.j]=t[l.j]||[];return t[l.j]}function D(a,c,b){t.addEventListener?a.addEventListener(c,b,!1):t.attachEvent&&a.attachEvent("on"+c,b)}function N(){var a;for(a=0;a<arguments.length;a++)try{var c=arguments[a].shift();this[c]&&"function"===typeof this[c]&&this[c].apply(this,arguments[a])}catch(b){}}function E(){var a;t.XMLHttpRequest?a=new t.XMLHttpRequest:t.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));return a}function P(a,c,b){a.open("GET","/store-participation?"+
c,!0);a.setRequestHeader("X-Part",b?b:"-")}function Oa(){var a=navigator.userAgent||navigator.vendor||window.opera;return-1<a.indexOf("FBAN")||-1<a.indexOf("FBAV")}function za(a){return"string"!==typeof a?{}:(a=a.trim().replace(/^(\?|#)/,""))?a.trim().split("&").reduce(function(c,b){var k=b.replace(/\+/g," ").split("="),u=k[0];k=k[1];u=da(u);k=void 0===k?null:da(k);c.hasOwnProperty(u)?Array.isArray(c[u])?c[u].push(k):c[u]=[c[u],k]:c[u]=k;return c},{}):{}}function Pa(a){if(z.search){var c=za(z.search),
b=/^utm_/,k;for(k in c)String(k).match(b)&&(a+=(a.length?"&":"")+ma(k)+"="+ma(c[k]))}return a}function Qa(){for(var a=0;a<na.length;a++)na[a]()}function Aa(a){Ba[a]||(na.push(function(){Aa(a)}),Ba[a]=!0);F&&F[a]&&d.H(a,"metadataUpdated",JSON.stringify(F[a]))}function Ra(a){try{F=JSON.parse(a),!1!==oa&&oa(F)}catch(c){}}function Sa(){var a=r.documentElement;null===O&&(O={x:void 0!==t.pageXOffset?t.pageXOffset:a.scrollLeft,y:void 0!==t.pageYOffset?t.pageYOffset:a.scrollTop})}function pa(){null!==O&&
(t.scrollTo(O.x,O.y),O=null)}function Ca(a){Sa();Da(function(){Ea(a);ea(l.g,l.g,a.b)},a,"init")}function Ea(a){function c(b){a.b.style[b]=Math.ceil(a[b])+"px"}h.na&&c(l.c);h.J&&c(l.h)}function Da(a,c,b){b!==c.type&&fa?fa(a):a()}function ea(a,c,b){if("0"!==b.parentNode.getAttribute(l.o)){a=b.parentNode.getAttribute(l.C);try{b.contentWindow.postMessage("[QIS]"+c,a)}catch(k){}if(a.match(/^http:\/\//))try{b.contentWindow.postMessage("[QIS]"+c,a.replace(/^http:\/\//,"https://"))}catch(k){}}}function Ta(){var a=
this,c=function(b){""===b&&(a.id=b="_qualiframe_"+Ua++);return b}(a.id);(function(){var b=h.scrolling;a.style.overflow=!1===b?"hidden":"auto";a.scrolling=!1===b?"no":"auto"})();(function(){function b(k){Infinity!==h[k]&&0!==h[k]&&h[k]&&(a.style[k]=h[k]+"px")}b(l.K);b(l.M);b(l.L);b(l.N)})();if("number"===typeof h.f||"0"===h.f)h.A=h.f,h.f=""+h.f+"px";(function(b){D(a,"load",function(){var k=Fa;ea("iFrame.onload",b,a);!k&&h.D in Va&&Ca({b:a,height:0,width:0,type:"init"})});ea("init",b,a)})([c,h.A,h.J,
h.Y,h.fa,h.Z,h.O,h.f,h.D,h.P,h.R,h.ra,ma(z.href)].join(":"))}if(!window._qual_async||!window._qual_async.createIframe){var Ga="*",Y=!1,ha=!1,F=!1,oa=!1,Ha=!1,t=window,r=t.document,z=r.location,Z=Math.max,qa=Math.abs,Q=Number,aa=parseInt,ma=encodeURIComponent,da=decodeURIComponent,l={c:"height",h:"width",sa:"auto",v:"click",g:"reset",M:"minHeight",K:"maxHeight",N:"minWidth",L:"maxWidth",j:"parentIFrame",G:"resetPage",C:"data-destination",u:"mutationObserver",o:"data-loaded"},T=function(){this.F("v1.cfm",
"qualifio-",!1)},d=T.prototype;d.F=function(a,c,b){this.$=a;this.ga=c;this.l=b;this.i={}};d.qa=function(a,c){var b=E();b.onreadystatechange=function(){};P(b,a,c);b.send()};d.ka=function(a,c){var b=E();b.onreadystatechange=function(){4==b.readyState&&200==b.status&&c(b.responseText)};P(b,a);b.send()};d.s=function(a){a=a.message;try{eval(a)}catch(c){}};d.m=function(a,c){c[l.c]=a[l.c]};d.ca=function(a){!1===Y?ha=a:a(Y)};d.da=function(a){Ha=a};d.X=function(a,c,b,k,u,B,R,K,I,U,L){function x(v,M){return v in
H?H[v]:M}I||(I=this.ga);I+=k;"auto"!=K&&(K="no");if(z.search){var q=za(z.search);q._fpv&&(b=""+Q(q._fpv))}Ga=z.protocol+"//"+c+"/";R=Pa(R);c=this.S(c,b,k,R,L);Oa()&&(c+="&fbappiframe=1");k=function(v){v="_qual_restore_"+v;var M={},y=r.cookie;if(""!==y){y=y.split("; ");for(var S=0;S<y.length;S++){var J=y[S],V=J.indexOf("="),W=J.substring(0,V);J=J.substring(V+1);try{J=da(J)}catch(ra){}M[W]=J}}return(v=M[v])?decodeURI(v):!1}(k);Ha||k&&(c=k);var H=this.i,g,p;k=r.createElement("IFRAME");u={id:I,name:I,
src:c,style:(B?l.c+":"+B+"px; ":"")+(U?U:""),width:x("width",u),frameborder:x("frameborder",0),hspace:x("hspace",0),vspace:x("vspace",0),"class":("_qIframe "+x("class","")).trim(),noresize:x("noresize","noresize")};for(g in this.i)g in u||(u[g]=this.i[g]);for(p in u)k.setAttribute(p,u[p]);var w=r.getElementById(a);w.setAttribute(l.C,Ga);w.setAttribute(l.o,"0");k.addEventListener("load",function(){w.setAttribute(l.o,"1")});w.appendChild(k);this.ha({resizedCallback:function(v,M){return function(y){v.m(y,
M)}}(this,w),messageCallback:this.s,scrolling:"no"!==K},k)};d.la=function(a){if(!a||a.constructor!==Object)throw new TypeError('Invalid parameter "'+a+'" for setIframeAttributes.');for(var c in a)c in{id:1,name:1,src:1,style:1}||(this.i[c]=a[c])};d.aa=function(){};d.S=function(a,c,b,k,u){z.origin||(z.origin=z.protocol+"//"+z.hostname+(z.port?":"+z.port:""));var B=aa(c,10);1<B&&19>B&&(c="20");B=this.$;u&&(B="s"+u+"/"+B);a="https://"+(a+"/"+(c?c+"/":"")+(b?b+"/":"")+B)+"?"+(b?"id="+b+"&":"")+"pdomain="+
z.origin;k&&(a=a+"&"+k);return a};d.setConfiguration=function(a){for(var c in a)!this[c]||this[c]&&"function"===typeof this[c]||!c.match("^target")&&(this[c]=a[c])};d.T=function(a){C().push(["sendMessage",a])};var ia=[],Ia=!1;d.B=function(a){if(Ia)a();else if(!0===a){for(a=0;a<ia.length;a++)ia[a]();ia=[];Ia=!0}else ia.push(a)};var na=[];d.oa=function(){this.l=!0};d.I=function(a){this.l=!0;C().push(["storePosition",a])};d.V=function(){this.l=!0;C().push(["clearPosition"])};d.ia=function(a){C().push(["redirectTo",
a])};d.scrollTo=function(a,c){C().push(["scrollTo",a,c])};d.ja=function(a,c){C().push(["registerParentMessageCallback",a,c])};d.H=function(a,c,b){(a=r.getElementById(a))&&(a=a.getElementsByTagName("IFRAME")[0])&&ea(c,["[CM]",c,":",b].join(""),a)};var Ba={};d.ma=function(a,c,b){b||(b="*");F=F||{};F[b]=F[b]||{};F[b][a]=c;Aa(b)};d.ba=function(a){oa=a;!1!==F&&a(F)};var ja=function(){},Ua=0,Fa=!0,O=null,fa=t.requestAnimationFrame,Va={max:1,scroll:1,bodyScroll:1,documentElementScroll:1},h={};d.pa=function(a){(function(){function c(){var f=
Ja.substr(5).split(":");sa=f[0];V=void 0!==f[1]?Q(f[1]):V;ta=void 0!==f[2]?"true"===f[2]?!0:!1:ta;X=void 0!==f[4]?Q(f[4]):X;ua=void 0!==f[5]?"true"===f[5]?!0:!1:ua;S=void 0!==f[6]?"true"===f[6]?!0:!1:S;W=f[7];G=void 0!==f[8]?f[8]:G;J=f[9];ra=f[10];ka=void 0!==f[11]?Q(f[11]):ka;Y=da(void 0!==f[12]?f[12]:"");if("function"==typeof ha&&"string"==typeof Y){try{ha(Y)}catch(m){}ha=!1}void 0===W&&(W=V+"px");b("margin",W);b("background",J);b("padding",ra);f=r.createElement("div");f.style.clear="both";f.style.display=
"block";r.body.appendChild(f);B();r.documentElement.style[l.c]="auto";b(l.c,"auto");!0===S&&(k(),u(),U());p("init","_");R()}function b(f,m){void 0!==m&&""!==m&&"null"!==m&&(r.body.style[f]=m)}function k(){D(t,"resize",function(){p("resize","_")})}function u(){D(t,l.v,function(){p(l.v,"_")})}function B(){"offset"!==G&&(G in va||(G="offset"))}function R(){if(ua){var f=C(),m={close:function(){p("close","parentIFrame.close()",0,0)},getId:function(){return sa},reset:function(){M("parentIFrame.size")},
scrollTo:function(e,n){-1===e?y(e,n,"[SF]"):y(e,n,"[ST]")},sendMessage:function(e,n){y(0,0,"msg",e,n)},redirectTo:function(e){y(0,0,"[GT]",e)},storePosition:function(e){y(0,0,"[SP]",e)},clearPosition:function(){y(0,0,"[QP]")},setHeightCalculationMethod:function(e){G=e;B()},setTargetOrigin:function(e){Ka=e},size:function(e,n){w();p("size","_",e,n)},registerParentMessageCallback:function(e,n){wa[e]=n}};m.push=N;t[l.j]=m;N.apply(m,f)}}function K(){0!==X&&setInterval(function(){p("interval","setInterval: "+
X)},qa(X))}function I(f){function m(e){void 0!==e[l.c]&&void 0!==e[l.h]&&0!==e[l.c]&&0!==e[l.h]||D(e,"load",function(){p("imageLoad","Image loaded")})}f.forEach(function(e){"attributes"===e.type&&"src"===e.attributeName?m(e.target):"childList"===e.type&&Array.prototype.forEach.call(e.target.querySelectorAll("img"),function(n){m(n)})})}function U(){function f(){var e=r.querySelector("body");(new m(function(n){p(l.u,l.u+": "+n[0].target+" "+n[0].type);I(n)})).observe(e,{attributes:!0,attributeOldValue:!1,
characterData:!0,characterDataOldValue:!1,childList:!0,subtree:!0})}var m=t[l.u]||t.WebKitMutationObserver;m?0>X?K():f():K()}function L(){function f(m){var e=r.body;if("defaultView"in r&&"getComputedStyle"in r.defaultView)e=r.defaultView.getComputedStyle(e,null),e=null!==e?e[m]:0;else if(m=e.currentStyle[m],/^\d+(px)?$/i.test(m))e=aa(m,10);else{var n=e.style.left,A=e.runtimeStyle.left;e.runtimeStyle.left=e.currentStyle.left;e.style.left=m||0;m=e.style.pixelLeft;e.style.left=n;e.runtimeStyle.left=
A;e=m}return aa(e,10)}return r.body.offsetHeight+f("marginTop")+f("marginBottom")}function x(){return r.body.scrollHeight}function q(){return r.documentElement.offsetHeight}function H(){return r.documentElement.scrollHeight}function g(){return Z.apply(null,[L(),x(),q(),H()])}function p(f,m,e,n){la&&f in Wa||(e=void 0!==e&&0>e?e:va[G](),n=void 0!==n&&0>n?n:Z(r.documentElement.scrollWidth,r.body.scrollWidth),qa(ba-e)<=ka&&(!ta||qa(ca-n)<=ka)?!(f in{init:1,interval:1,size:1})&&G in Xa&&M(m):(w(),ba=
e,ca=n,y(ba,ca,f)))}function w(){la||(la=!0);clearTimeout(La);La=setTimeout(function(){la=!1},128)}function v(f){ba=va[G]();ca=Z(r.documentElement.scrollWidth,r.body.scrollWidth);y(ba,ca,f)}function M(){var f=G;G="offset";w();v(l.g);G=f}function y(f,m,e,n,A){void 0===A&&(A=Ka);m=[sa,f,m,e];void 0!==n&&m.push(n);n=m.join(":");try{if(f){try{xa.postMessage({sentinel:"amp",type:"embed-size",height:f},"*")}catch(ya){}try{window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers["native"]&&
window.webkit.messageHandlers["native"].postMessage&&window.webkit.messageHandlers["native"].postMessage({sentinel:"amp",type:"embed-size",height:f})}catch(ya){}}xa.postMessage("[QIS]"+n,A)}catch(ya){}}var S=!0,J="",V=0,W="",ra="",ta=!1,Wa={resize:1,click:1},ba=1,Ma=!0,G="offset",Na=!0,Ja="",X=32,sa="",ua=!0,Xa={max:1,scroll:1,ta:1,ua:0},Ka=a?a:"*",xa=t.parent,ka=0,la=!1,La=null,ca=1,wa={metadataUpdated:Ra},va={offset:L,bodyOffset:L,bodyScroll:x,documentElementOffset:q,scroll:H,documentElementScroll:H,
max:g,min:function(){return Math.min.apply(null,[L(),x(),q(),H()])},grow:g,lowestElement:function(){for(var f=L(),m=r.querySelectorAll("body *"),e=m.length,n=0,A=0;A<e;A++)"OPTION"!=m[A].tagName.toUpperCase()&&(n=Z(m[A].getBoundingClientRect().bottom,n));return Z(f,n)}};D(t,"message",function(f){function m(){Ja=f.data;xa=f.source;c();Ma=!1;setTimeout(function(){Na=!1},128)}function e(n){var A=n.data.slice(9).split(":");n=A[0];A=A.slice(1).join(":");if(wa[n])try{wa[n](A)}catch(ya){}}"[QIS]"===(""+
f.data).substr(0,5)&&(Ma&&f.data.split(":")[2]in{"true":1,"false":1}?m():l.g===f.data.split("]")[1]?Na||v(l.G):"[CM]"===f.data.split("]")[1]+"]"&&e(f))});"*"===a&&c()})();this.l||this.I(z.href)};(function(){var a=["moz","webkit","o","ms"],c;for(c=0;c<a.length&&!fa;c+=1)fa=t[a[c]+"RequestAnimationFrame"]})();D(t,"message",function(a){function c(){Da(function(){Ea(q);pa();h.m(q)},q,l.G)}function b(g){var p=g.id;g.parentNode.removeChild(g);h.W(p)}function k(){var g=x.substr(5).split(":");return{b:r.getElementById(g[0]),
id:g[0],height:g[1],width:g[2],type:g[3],data:g.slice(4).join(":")}}function u(g){var p=Q(h["max"+g]),w=Q(h["min"+g]),v=Q(q[g]);if(w>p)throw Error("");v<w&&(v=w);v>p&&(v=p);q[g]=""+v}function B(){var g=a.origin,p=q.b.src.split("/").slice(0,3).join("/");if(h.U&&"null"!==""+g&&g!==p&&g!==p.replace(/^http:\/\//,"https://"))throw Error("");return!0}function R(){var g=r.getElementById(q.b.id);if(g.getBoundingClientRect){g=g.getBoundingClientRect();var p=r.body,w=r.documentElement;g={top:Math.round(g.top+
(window.pageYOffset||w.scrollTop||p.scrollTop)-(w.clientTop||p.clientTop||0)),left:Math.round(g.left+(window.pageXOffset||w.scrollLeft||p.scrollLeft)-(w.clientLeft||p.clientLeft||0))}}else{for(w=p=0;g;)p+=aa(g.offsetTop,10),w+=aa(g.offsetLeft,10),g=g.offsetParent;g={top:p,left:w}}O={x:g.left,y:g.top};pa()}function K(g,p,w){var v=new Date;v.setMinutes(v.getMinutes()+w);r.cookie=g+"="+encodeURI(p)+"; expires="+v.toUTCString()}function I(){var g="";q.b&&q.b.id&&(g=q.b.id,g=g.substr(g.length-36,36));
return g}function U(){var g=I();K("_qual_restore_"+g,"d",-20)}function L(){var g=I();K("_qual_restore_"+g,x.substr(x.indexOf(":")+q.type.length+6),20)}var x=a.data,q={};if("[QIS]"===(""+x).substr(0,5)){q=k();u(l.c);u(l.h);try{var H;if(H=!(q.type in{"true":1,"false":1})){if(null===q.b)throw Error("");H=!0}if(H&&B()){switch(q.type){case "close":b(q.b);h.m(q);break;case "msg":h.s({b:q.b,message:x.substr(x.indexOf(":")+3+6)});break;case "[ST]":O={x:q[l.h],y:q[l.c]};pa();break;case "[SF]":R();break;case "[GT]":z.href=
x.substr(x.indexOf(":")+q.type.length+6);break;case "[SP]":L();break;case "[QP]":U();break;case l.g:Ca(q);break;case "init":c();Qa();h.ea(q.b);break;default:c()}Fa=!1}}catch(g){}}});d.ha=function(){return function(a,c){var b=a||{};if("object"!==typeof b)throw new TypeError("");b.a=b.hasOwnProperty;h.O=b.a("autoResize")?b.autoResize:!0;h.P=b.a("bodyBackground")?b.bodyBackground:null;h.f=b.a("bodyMargin")?b.bodyMargin:null;h.A=b.a("bodyMarginV1")?b.bodyMarginV1:8;h.R=b.a("bodyPadding")?b.bodyPadding:
null;h.U=b.a("checkOrigin")?b.checkOrigin:!0;h.Z=b.a("enablePublicMethods")?b.enablePublicMethods:!0;h.D=b.a("heightCalculationMethod")?b.heightCalculationMethod:"lowestElement";h.fa=b.a("pollInterval")?b.pollInterval:8;h.Y=b.a("enableLog")?b.enableLog:!1;h.scrolling=b.a("scrolling")?b.scrolling:!1;h.na=b.a("sizeHeight")?b.sizeHeight:!0;h.J=b.a("sizeWidth")?b.sizeWidth:!1;h.ra=b.a("tolerance")?b.tolerance:0;h.W=b.a("closedCallback")?b.closedCallback:ja;h.ea=b.a("initCallback")?b.initCallback:ja;h.s=
b.a("messageCallback")?b.messageCallback:ja;h.m=b.a("resizedCallback")?b.resizedCallback:ja;if("IFRAME"!==c.tagName.toUpperCase())throw new TypeError("");Ta.call(c)}}();d.push=N;d.storeParticipationData=d.qa;d.retrieveParticipationData=d.ka;d.createIframe=d.X;d.setIframeAttributes=d.la;d.startChildIframe=d.pa;d.callParentFunction=d.T;d.setIframeUrl=d.I;d.skipIframeUrlStorage=d.oa;d.clearIframeUrl=d.V;d.redirectParentTo=d.ia;d.callOnIframeLoad=d.B;d.scrollTo=d.scrollTo;d.sendChildMessage=d.H;d.registerParentMessageCallback=
d.ja;d.getParentLocation=d.ca;d.ignoreRestoreCookie=d.da;d.forceHTTPS=d.aa;d.init=d.F;d.setMetaData=d.ma;d.getMetaData=d.ba;if(!window._qual_async||!window._qual_async.createIframe){var Ya=t._qual_async;T=new T;t._qual_async=T;N.apply(T,Ya);T.B(!0)}}})();